DELETE FROM game_abbreviations;


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gd', 'Game Development');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gamedev', 'Game Development');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe', 'Age of Empires');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoerr', 'Age of Empires: The Rise of Rome');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2aok', 'Age of Empires II: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2tc', 'Age of Empires II: The Conquerors');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2hd', 'Age of Empires II: HD Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2aok', 'Age of Empires II: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aom', 'Age of Mythology');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aomtt', 'Age of Mythology: The Titans');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aomee', 'Age of Mythology: Extended Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe3twc', 'Age of Empires III: The WarChiefs');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe3tad', 'Age of Empires III: The Asian Dynasties');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoeo', 'Age of Empires Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoecs', 'Age of Empires: Castle Siege');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoetok', 'Age of Empires: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoem', 'Age of Empires: Mythologies');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngreen', 'Pokémon Green');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnredblue', 'Pokémon Red/Blue');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrb', 'Pokémon Red/Blue');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnyellow', 'Pokémon Yellow: Special Pikachu Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmny', 'Pokémon Yellow: Special Pikachu Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngoldsilver', 'Pokémon Gold/Silver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngs', 'Pokémon Gold/Silver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmncrystal', 'Pokémon Crystal');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrubysapphire', 'Pokémon Ruby/Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrs', 'Pokémon Ruby/Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnemerald', 'Pokémon Emerald');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmne', 'Pokémon Emerald');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnfrlg', 'Pokémon FireRed/LeafGreen');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmndp', 'Pokémon Diamond/Pearl');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnplat', 'Pokémon Platinum');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnhgss', 'Pokémon HeartGold/SoulSilver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnblackwhite', 'Pokémon Black/White');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbw', 'Pokémon Black/White');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnblackwhite2', 'Pokémon Black/White Version 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnb2w2', 'Pokémon Black/White Version 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnxy', 'Pokémon X/Y');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnoras', 'Pokémon Omega Ruby/Alpha Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemontcg', 'Pokémon Trading Card Game');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnstadium', 'Pokémon Stadium');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnstadium2', 'Pokémon Stadium 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemoncol', 'Pokémon Colosseum');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemonxd', 'Pokémon XD: Gale of Darkness');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemonbr', 'Pokémon Battle Revolution');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnsnap', 'Pokémon Snap');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('hypikachu', 'Hey You, Pikachu!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnchannel', 'Pokémon Channel');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemate', 'Pokémate');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbattrio', 'Pokémon Battrio');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mpkmnr', 'My Pokémon Ranch');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnconquest', 'Pokémon Conquest');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pknt', 'Pokkén Tournament');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmndash', 'Pokémate');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ppc', 'Pokémon Puzzle Challenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ppl', 'Pokémon Puzzle League');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmntrozei', 'Pokémon Trozei!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbt', 'Pokémon Battle Trozei');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdredblue', 'Pokémon Mystery Dungeon: Blue/Red Rescue Team');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdeodt', 'Pokémon Mystery Dungeon: Explorers of Darkness/Time');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdeos', 'Pokémon Mystery Dungeon: Explorers of Sky');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdgti', 'Pokémon Mystery Dungeon: Gates to Infinity');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnpinball', 'Pokémon Pinball');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnpbrs', 'Pokémon Pinball: Ruby & Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumble', 'Pokémon Rumble');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumbleblast', 'Pokémon Rumble Blast');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumbleu', 'Pokémon Rumble U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnranger', 'Pokémon Ranger');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrangersoa', 'Pokémon Ranger: Shadows of Almia');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrangergs', 'Pokémon Ranger: Guardian Signs');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokeparkwii', 'PokéPark Wii: Pikachu''s Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokepark2', 'PokéPark 2: Wonders Beyond');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm1', 'Mega Man');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2', 'Mega Man 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3', 'Mega Man 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3rr', 'Mega Man 3: The Robots are Revolting');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm4', 'Mega Man 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm5', 'Mega Man 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm6', 'Mega Man 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm7', 'Mega Man 7');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm8', 'Mega Man 8: Anniversary Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm9', 'Mega Man 9');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm10', 'Mega Man 10');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmww', 'Mega Man: The Wily Wars');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmac', 'Mega Man Anniversary Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmf', 'Mega Man & Bass');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmb', 'Mega Man & Bass');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmfmknc', 'Rockman & Forte: Mirai kara no Chousensha');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm1gb', 'Mega Man: Dr Wily''s Revenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2gb', 'Mega Man II');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3gb', 'Mega Man III');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm4gb', 'Mega Man IV');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm5gb', 'Mega Man V');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx', 'Mega Man X');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx2', 'Mega Man X2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx3', 'Mega Man X3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx4', 'Mega Man X4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx5', 'Mega Man X5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx6', 'Mega Man X6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx7', 'Mega Man X7');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx8', 'Mega Man X8');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxc', 'Mega Man X Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxgb', 'Mega Man Xtreme');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx2gb', 'Mega Man Xtreme 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxcm', 'Mega Man X: Command Mission');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz', 'Mega Man Zero');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz2', 'Mega Man Zero 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz3', 'Mega Man Zero 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz4', 'Mega Man Zero 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzc', 'Mega Man Zero Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzx', 'Mega Man ZX');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzxa', 'Mega Man ZX Advent');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn1', 'Mega Man Battle Network');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn2', 'Mega Man Battle Network 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn3', 'Mega Man Battle Network 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn4', 'Mega Man Battle Network 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn4.5', 'Rockman EXE 4.5 Real Operation');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn5', 'Mega Man Battle Network 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn5ds', 'Mega Man Battle Network 5: Double Team DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn6', 'Mega Man Battle Network 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf1', 'Mega Man Star Force');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf2', 'Mega Man Star Force 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf3', 'Mega Man Star Force 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbcc', 'Mega Man Battle Chip Challenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmeoss', 'Rockman EXE Operate Shooting Star');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbncx', 'Mega Man Battle Network Chrono X');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmtpb', 'Mega Man: The Power Battle');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2tbf', 'Mega Man 2: The Power Fighters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmbf', 'Rockman Battle & Fighters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm64', 'Mega Man 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mml', 'Mega Man Legends');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mml2', 'Mega Man Legends 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmbc', 'Rockman Battle & Chase');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb1', 'Super Mario Bros.');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb1ll', 'Super Mario Bros.: The Lost Levels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb2j', 'Super Mario Bros.: The Lost Levels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb2', 'Super Mario Bros. 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb3', 'Super Mario Bros. 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smw', 'Super Mario World');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smw2', 'Super Mario World 2: Yoshi''s Island');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm64', 'Super Mario 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sms', 'Super Mario Sunshine');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('luigismansion', 'Luigi''s Mansion');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmbwii', 'New Super Mario Bros. Wii');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smg1', 'Super Mario Galaxy');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smg2', 'Super Mario Galaxy 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmbu', 'New Super Mario Bros. U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nslu', 'New Super Luigi U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm3dw', 'Super Mario 3D World');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('capttoadtt', 'Captain Toad: Treasure Tracker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sml1', 'Super Mario Land');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sml2', 'Super Mario Land 2: 6 Golden Coins');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smbdx', 'Super Mario Bros. Deluxe');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl1', 'Wario Land: Super Mario Land 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl2', 'Wario Land II');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl3', 'Wario Land 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl4', 'Wario Land 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma1', 'Super Mario Advance');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma2', 'Super Mario World: Super Mario Advance 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma3', 'Yoshi''s Island: Super Mario Advance 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma4', 'Super Mario Bros. 3: Super Mario Advance 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm64ds', 'Super Mario 64 DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmb', 'New Super Mario Bros.');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yids', 'Yoshi''s Island DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm3dl', 'Super Mario 3D Land');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('luigismansiondm', 'Luigi''s Mansion: Dark Moon');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smrpg', 'Super Mario RPG: Legend of the Seven Stars');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmario', 'Paper Mario');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmttyd', 'Paper Mario: The Thousand-Year Door');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('superpaperm', 'Super Paper Mario');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmarioss', 'Paper Mario: Sticker Star');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smk', 'Super Mario Kart');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk64', 'Mario Kart 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkdd', 'Mario Kart: Double Dash!!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkwii', 'Mario Kart Wii');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk8', 'Mario Kart 8');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mksc', 'Mario Kart: Super Circuit');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkds', 'Mario Kart DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk7', 'Mario Kart 7');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gdash', 'Geometry Dash');
