dist: trusty
sudo: false
language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
      - sqlite3
      - unixodbc-dev
      - libsqliteodbc
      - postgresql-9.5
      - odbc-postgresql
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -r requirements-test.txt
before_script:
  - psql -U postgres -c 'CREATE ROLE botgotsthis_test'
  - psql -U postgres -c "ALTER ROLE botgotsthis_test WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION BYPASSRLS PASSWORD 'md5b3591780cc0946affe0bb30ed8c31736'"
  - psql -U postgres -c 'CREATE DATABASE botgotsthis_test WITH OWNER = botgotsthis_test'
script:
  - python -m unittest discover -s ./tests/unittest -t ./ -p test_*.py
  - python -m unittest discover -s ./pkg -t ./ -p test_*.py
  - python -m unittest discover -s ./tests/database -t ./ -p test_*.py
  - python -m unittest discover -s ./tests/integrationtest -t ./ -p test_*.py
  - mypy main.py
  - mypy pkg/botgotsthis/mypy-test.py
  - mypy pkg/custom_command/mypy-test.py
  - mypy pkg/feature/mypy-test.py
  - mypy pkg/moderation/mypy-test.py
  - mypy pkg/repeat/mypy-test.py
  - mypy pkg/spam/mypy-test.py
  - mypy pkg/textformat/mypy-test.py
  - mypy pkg/twitch/mypy-test.py
  - flake8
