language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
      - sqlite3
      - unixodbc-dev
      - libsqliteodbc
install:
  - pip install -r requirements-test.txt
script:
  - python -m unittest discover -s ./tests/unittest -t ./tests/unittest -p test_*.py
