language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
      - sqlite3
      - unixodbc-dev
      - libsqliteodbc
install:
  - pip install -r requirements-test.txt
script:
  - python -m unittest discover -s ./tests/unittest -t ./tests/unittest -p test_*.py
  - python -m unittest discover -s ./tests/database -t ./tests/database -p test_*.py
  - python -m unittest discover -s ./tests/integrationtest -t ./tests/integrationtest -p test_*.py
  - mypy mypy-test.py
  - flake8
