BEGIN TRANSACTION;

DELETE FROM game_abbreviations;


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gd', 'Game Development');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gamedev', 'Game Development');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('creative', 'Creative');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('music', 'Music');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gts', 'Gaming Talk Shows');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('talkshow', 'Gaming Talk Shows');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gametalkshow', 'Gaming Talk Shows');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('poker', 'Poker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('blackjack', 'Blackjack');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pinball', 'Pinball');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('twitchplays', 'Twitch Plays');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('socialeating', 'Social Eating');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('seating', 'Social Eating');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('eating', 'Social Eating');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gamesdemoes', 'Games + Demos');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('demoes', 'Games + Demos');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('demo', 'Games + Demos');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('retro', 'Retro');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('bg', 'Board Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('boardgames', 'Board Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('bgl', 'Board Games Live');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('bgo', 'Board Game Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('bgc', 'Board Game Classics');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tabletop', 'Tabletop Simulator');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tabletops', 'Tabletop Simulator');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('poker', 'Poker');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('lol', 'League of Legends');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('heartstone', 'Hearthstone: Heroes of Warcraft');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('codbo3', 'Call of Duty: Black Ops III');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('dota2', 'Dota 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('minecraft', 'Minecraft');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('h1z1', 'H1Z1');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('destiny', 'Destiny');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wot', 'World of Tanks');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wow', 'World of Warcraft');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smite', 'Smite');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('overwatch', 'Overwatch');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('battlefield1', 'Battlefield 1');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('hots', 'Heroes of the Storm');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smite', 'Smite');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('cs', 'Half-Life: Counter-Strike');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('hfcs', 'Half-Life: Counter-Strike');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('cscz', 'Counter-Strike: Condition Zero');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('cssource', 'Counter-Strike: Source');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('csgo', 'Counter-Strike: Global Offensive');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('csneo', 'Counter-Strike Neo');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('csonline', 'Counter-Strike Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('csnexon', 'Counter-Strike Nexon: Zombies');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('boi', 'The Binding of Isaac');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('boir', 'The Binding of Isaac: Rebirth');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('boia', 'The Binding of Isaac: Afterbirth');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sc', 'StarCraft: Brood War');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sc2', 'StarCraft II');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe', 'Age of Empires');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoerr', 'Age of Empires: The Rise of Rome');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2aok', 'Age of Empires II: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2tc', 'Age of Empires II: The Conquerors');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2hd', 'Age of Empires II: HD Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe2aok', 'Age of Empires II: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aom', 'Age of Mythology');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aomtt', 'Age of Mythology: The Titans');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aomee', 'Age of Mythology: Extended Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe3', 'Age of Empires III');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe3twc', 'Age of Empires III: The WarChiefs');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoe3tad', 'Age of Empires III: The Asian Dynasties');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoeo', 'Age of Empires Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoecs', 'Age of Empires: Castle Siege');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoetok', 'Age of Empires: The Age of Kings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('aoem', 'Age of Empires: Mythologies');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngreen', 'Pokémon Green');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnredblue', 'Pokémon Red/Blue');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrb', 'Pokémon Red/Blue');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnyellow', 'Pokémon Yellow: Special Pikachu Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmny', 'Pokémon Yellow: Special Pikachu Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngoldsilver', 'Pokémon Gold/Silver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngs', 'Pokémon Gold/Silver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmncrystal', 'Pokémon Crystal');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrubysapphire', 'Pokémon Ruby/Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrs', 'Pokémon Ruby/Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnemerald', 'Pokémon Emerald');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmne', 'Pokémon Emerald');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnfrlg', 'Pokémon FireRed/LeafGreen');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmndp', 'Pokémon Diamond/Pearl');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnplat', 'Pokémon Platinum');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnhgss', 'Pokémon HeartGold/SoulSilver');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnblackwhite', 'Pokémon Black/White');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbw', 'Pokémon Black/White');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnblackwhite2', 'Pokémon Black/White Version 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnb2w2', 'Pokémon Black/White Version 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnxy', 'Pokémon X/Y');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnoras', 'Pokémon Omega Ruby/Alpha Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnsunmoon', 'Pokémon Sun/Moon');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnsm', 'Pokémon Sun/Moon');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemontcg', 'Pokémon Trading Card Game');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnstadium', 'Pokémon Stadium');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnstadium2', 'Pokémon Stadium 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemoncol', 'Pokémon Colosseum');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemonxd', 'Pokémon XD: Gale of Darkness');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemonbr', 'Pokémon Battle Revolution');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnsnap', 'Pokémon Snap');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('hypikachu', 'Hey You, Pikachu!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnchannel', 'Pokémon Channel');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemate', 'Pokémate');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbattrio', 'Pokémon Battrio');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mpkmnr', 'My Pokémon Ranch');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnconquest', 'Pokémon Conquest');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pknt', 'Pokkén Tournament');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmndash', 'Pokémate');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ppc', 'Pokémon Puzzle Challenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ppl', 'Pokémon Puzzle League');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmntrozei', 'Pokémon Trozei!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnbt', 'Pokémon Battle Trozei');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdredblue', 'Pokémon Mystery Dungeon: Blue/Red Rescue Team');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdeodt', 'Pokémon Mystery Dungeon: Explorers of Darkness/Time');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdeos', 'Pokémon Mystery Dungeon: Explorers of Sky');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmdgti', 'Pokémon Mystery Dungeon: Gates to Infinity');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('psmd', 'Pokémon Super Mystery Dungeon');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnpinball', 'Pokémon Pinball');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnpbrs', 'Pokémon Pinball: Ruby & Sapphire');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumble', 'Pokémon Rumble');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumbleblast', 'Pokémon Rumble Blast');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumbleu', 'Pokémon Rumble U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrumbleworld', 'Pokémon Rumble World');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnranger', 'Pokémon Ranger');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrangersoa', 'Pokémon Ranger: Shadows of Almia');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnrangergs', 'Pokémon Ranger: Guardian Signs');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokeparkwii', 'PokéPark Wii: Pikachu''s Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokepark2', 'PokéPark 2: Wonders Beyond');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmntcgo', 'Pokémon Trading Card Game Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokemontcgo', 'Pokémon Trading Card Game Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('popi', 'Pokémon Picross');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmnpicross', 'Pokémon Picross');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pokken', 'Pokkén Tournament');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pkmngo', 'Pokémon Go');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm1', 'Mega Man');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2', 'Mega Man 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3', 'Mega Man 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3rr', 'Mega Man 3: The Robots are Revolting');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm4', 'Mega Man 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm5', 'Mega Man 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm6', 'Mega Man 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm7', 'Mega Man 7');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm8', 'Mega Man 8: Anniversary Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm9', 'Mega Man 9');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm10', 'Mega Man 10');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmww', 'Mega Man: The Wily Wars');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmac', 'Mega Man Anniversary Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmf', 'Mega Man & Bass');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmb', 'Mega Man & Bass');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmfmknc', 'Rockman & Forte: Mirai kara no Chousensha');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm1gb', 'Mega Man: Dr Wily''s Revenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2gb', 'Mega Man II');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3gb', 'Mega Man III');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm4gb', 'Mega Man IV');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm5gb', 'Mega Man V');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx', 'Mega Man X');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx2', 'Mega Man X2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx3', 'Mega Man X3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx4', 'Mega Man X4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx5', 'Mega Man X5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx6', 'Mega Man X6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx7', 'Mega Man X7');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx8', 'Mega Man X8');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxc', 'Mega Man X Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxgb', 'Mega Man Xtreme');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmx2gb', 'Mega Man Xtreme 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmxcm', 'Mega Man X: Command Mission');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz', 'Mega Man Zero');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz2', 'Mega Man Zero 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz3', 'Mega Man Zero 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmz4', 'Mega Man Zero 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzc', 'Mega Man Zero Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzx', 'Mega Man ZX');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmzxa', 'Mega Man ZX Advent');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn1', 'Mega Man Battle Network');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn2', 'Mega Man Battle Network 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn3', 'Mega Man Battle Network 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn4', 'Mega Man Battle Network 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn4.5', 'Rockman EXE 4.5 Real Operation');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn5', 'Mega Man Battle Network 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn5ds', 'Mega Man Battle Network 5: Double Team DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbn6', 'Mega Man Battle Network 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf1', 'Mega Man Star Force');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf2', 'Mega Man Star Force 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmsf3', 'Mega Man Star Force 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbcc', 'Mega Man Battle Chip Challenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmeoss', 'Rockman EXE Operate Shooting Star');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmbncx', 'Mega Man Battle Network Chrono X');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mmtpb', 'Mega Man: The Power Battle');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm2tbf', 'Mega Man 2: The Power Fighters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmbf', 'Rockman Battle & Fighters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm64', 'Mega Man 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mml', 'Mega Man Legends');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mml2', 'Mega Man Legends 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('rmbc', 'Rockman Battle & Chase');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb1', 'Super Mario Bros.');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb1ll', 'Super Mario Bros.: The Lost Levels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb2j', 'Super Mario Bros.: The Lost Levels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb2', 'Super Mario Bros. 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smb3', 'Super Mario Bros. 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smw', 'Super Mario World');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smw2', 'Super Mario World 2: Yoshi''s Island');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm64', 'Super Mario 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sms', 'Super Mario Sunshine');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('luigismansion', 'Luigi''s Mansion');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmbwii', 'New Super Mario Bros. Wii');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smg1', 'Super Mario Galaxy');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smg2', 'Super Mario Galaxy 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmbu', 'New Super Mario Bros. U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nslu', 'New Super Luigi U');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm3dw', 'Super Mario 3D World');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('capttoadtt', 'Captain Toad: Treasure Tracker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariomaker', 'Super Mario Maker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smm', 'Super Mario Maker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sml1', 'Super Mario Land');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sml2', 'Super Mario Land 2: 6 Golden Coins');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smbdx', 'Super Mario Bros. Deluxe');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl1', 'Wario Land: Super Mario Land 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl2', 'Wario Land II');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl3', 'Wario Land 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wl4', 'Wario Land 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma1', 'Super Mario Advance');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma2', 'Super Mario World: Super Mario Advance 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma3', 'Yoshi''s Island: Super Mario Advance 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sma4', 'Super Mario Bros. 3: Super Mario Advance 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm64ds', 'Super Mario 64 DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('nsmb', 'New Super Mario Bros.');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yids', 'Yoshi''s Island DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sm3dl', 'Super Mario 3D Land');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('luigismansiondm', 'Luigi''s Mansion: Dark Moon');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smrpg', 'Super Mario RPG: Legend of the Seven Stars');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmario', 'Paper Mario');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmttyd', 'Paper Mario: The Thousand-Year Door');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('superpaperm', 'Super Paper Mario');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmarioss', 'Paper Mario: Sticker Star');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('pmcs', 'Paper Mario: Color Splash');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mlss', 'Mario & Luigi: Superstar Saga');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mlpit', 'Mario & Luigi: Partners in Time');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mlbis', 'Mario & Luigi: Bowser''s Inside Story');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mldt', 'Mario & Luigi: Dream Team');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mlpj', 'Mario & Luigi: Paper Jam');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smk', 'Super Mario Kart');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk64', 'Mario Kart 64');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkdd', 'Mario Kart: Double Dash!!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkwii', 'Mario Kart Wii');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk8', 'Mario Kart 8');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mksc', 'Mario Kart: Super Circuit');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mkds', 'Mario Kart DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mk7', 'Mario Kart 7');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty', 'Mario Party');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty1', 'Mario Party');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty2', 'Mario Party 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty3', 'Mario Party 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty4', 'Mario Party 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty5', 'Mario Party 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty6', 'Mario Party 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty7', 'Mario Party 7');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariopartya', 'Mario Party Advance');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty8', 'Mario Party 8');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariopartyds', 'Mario Party DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty9', 'Mario Party 9');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariopartyit', 'Mario Party: Island Tour');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('marioparty10', 'Mario Party 10');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariopartysr', 'Mario Party: Star Rush');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ys', 'Yoshi''s Story');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ytt', 'Yoshi Topsy-Turvy');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ytag', 'Yoshi Touch & Go');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yids', 'Yoshi''s Island DS');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yni', 'Yoshi''s New Island');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yww', 'Yoshi''s Woolly World');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yoshi', 'Yoshi');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ycookie', 'Yoshi''s Cookie');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ysafari', 'Yoshi''s Safari');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tloz', 'The Legend of Zelda');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('zelda2', 'Zelda II: The Adventure of Link');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('alttp', 'The Legend of Zelda: A Link to the Past');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('lozla', 'The Legend of Zelda: Link''s Awakening');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('oot', 'The Legend of Zelda: Ocarina of Time');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm', 'The Legend of Zelda: Majora''s Mask');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('oos', 'The Legend of Zelda: Oracle of Seasons');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ooa', 'The Legend of Zelda: Oracle of Ages');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tww', 'The Legend of Zelda: The Wind Waker');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tlozfsa', 'The Legend of Zelda: Four Swords Adventures');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tp', 'The Legend of Zelda: Twilight Princess');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tmc', 'The Legend of Zelda: The Minish Cap');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('skywardsword', 'The Legend of Zelda: Skyward Sword');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tlozss', 'The Legend of Zelda: Skyward Sword');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ph', 'The Legend of Zelda: Phantom Hourglass');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spirittracks', 'The Legend of Zelda: Spirit Tracks');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tlozst', 'The Legend of Zelda: Spirit Tracks');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('albw', 'The Legend of Zelda: A Link Between Worlds');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tfh', 'The Legend of Zelda: Tri Force Heroes');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('botw', 'The Legend of Zelda: Breath of the Wild');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ladx', 'The Legend of Zelda: Link''s Awakening DX');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ootmq', 'The Legend of Zelda: Ocarina of Time / Master Quest');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tlozce', 'The Legend of Zelda: Collector''s Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('alttpff', 'The Legend of Zelda: A Link to the Past & Four Swords');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('fourswords', 'The Legend Of Zelda: Four Swords Anniversary Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tlozfsae', 'The Legend Of Zelda: Four Swords Anniversary Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('oot3d', 'The Legend of Zelda: Ocarina of Time 3D');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mm3d', 'The Legend of Zelda: Majora''s Mask 3D');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('twwhd', 'The Legend of Zelda: The Wind Waker HD');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tphd', 'The Legend of Zelda: Twilight Princess HD');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('lct', 'Link''s Crossbow Training');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('hw', 'Hyrule Warriors');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic1', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic1romhacks', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s1gg', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s1sms', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s1gba', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic2013', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic2', 'Sonic the Hedgehog 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic2romhacks', 'Sonic the Hedgehog 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s2rr', 'Sonic the Hedgehog 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s2gg', 'Sonic the Hedgehog 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s2sms', 'Sonic the Hedgehog 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('soniccd', 'Sonic CD');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('schaos', 'Sonic the Hedgehog Chaos');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic3', 'Sonic the Hedgehog 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicandknuckles', 'Sonic & Knuckles');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s3kme', 'Sonic 3 and Knuckles Master Edition');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('stt', 'Sonic Triple Trouble');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('kchaotix', 'Knuckles'' Chaotix');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicblast', 'Sonic Blast');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicpocketadventure', 'Sonic the Hedgehog Pocket Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadv', 'Sonic Advance');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadv2', 'Sonic Advance 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadv3', 'Sonic Advance 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicrush', 'Sonic Rush');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('srushadv', 'Sonic Rush Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s4e1', 'Sonic the Hedgehog 4: Episode I');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s4e2', 'Sonic the Hedgehog 4: Episode II');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s3d', 'Sonic 3D Blast');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('s3dblast', 'Sonic 3D Blast');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadv', 'Sonic Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadx', 'Sonic Adventure DX: Director''s Cut');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sadv2', 'Sonic Adventure 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sa2b', 'Sonic Adventure 2: Battle');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sheroes', 'Sonic Heroes');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('shadowth', 'Shadow the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonic06', 'Sonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ssecretrings', 'Sonic and the Secret Rings');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sunleased', 'Sonic Unleashed');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('su360', 'Sonic Unleashed');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('suwii', 'Sonic Unleashed');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('satbk', 'Sonic and the Black Knight');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('scolors', 'Sonic Colors');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('scolorsds', 'Sonic Colors');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicgenerations', 'Sonic Generations');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('soniclw', 'Sonic Lost World');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sdrift', 'Sonic Drift');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sdrift2', 'Sonic Drift 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicr', 'Sonic R');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicriders', 'Sonic Riders');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicrivals', 'Sonic Rivals');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicrivals2', 'Sonic Rivals 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicriderszg', 'Sonic Riders: Zero Gravity');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('asr', 'Sonic & Sega All-Stars Racing');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sfreeriders', 'Sonic Free Riders');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicasrt', 'Sonic & All-Stars Racing Transformed');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('segasoniccf', 'SegaSonic Cosmo Fighter');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('wwsonicpc', 'Waku Waku Sonic Patrol Car');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('segasonic', 'SegaSonic the Hedgehog');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('stf', 'Sonic the Fighters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicathletics', 'Sonic Athletics');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tailsmusicmaker', 'Tails and the Music Maker');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicschoolhouse', 'Sonic Eraser');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('robotnikmbm', 'Dr. Robotnik''s Mean Bean Machine');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicspinball', 'Sonic the Hedgehog: Spinball');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('skypatrol', 'Tails'' Skypatrol');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('tailsadv', 'Tails Adventure');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('soniclabyrinth', 'Sonic Labyrinth');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicshuffle', 'Sonic Shuffle');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicpp', 'Sonic Pinball Party');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicspinball', 'Sonic Pinball Party');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicbattle', 'Sonic Battle');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariosonicolympic', 'Mario & Sonic at the Olympic Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('scdarkbrotherhood', 'Sonic Chronicles: The Dark Brotherhood');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicjump', 'Sonic Jump');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicjumpfever', 'Sonic Jump Fever');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicdash', 'Sonic Dash');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicboomrol', 'Sonic Boom: Rise of Lyric');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicboomsc', 'Sonic Boom: Shattered Crystal');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicboomfi', 'Sonic Boom: Fire & Ice');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicmania', 'Sonic Mania');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariosonicwinterolympic', 'Mario & Sonic at the Olympic Winter Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ms2010', 'Mario & Sonic at the Olympic Winter Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariosonic2012olympic', 'Mario & Sonic at the London 2012 Olympic Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ms2012', 'Mario & Sonic at the London 2012 Olympic Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('mariosonic2014winterolympic', 'Mario & Sonic at the Sochi 2014 Winter Olympic Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ms2014', 'Mario & Sonic at the Sochi 2014 Winter Olympic Games');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ms2016', 'Mario & Sonic at the Rio 2016 Olympic Games');

INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sonicclassics', 'Sonic Classics: 3-in-1');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('skcollection', 'Sonic & Knuckles');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sjam', 'Sonic Jam');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smegacollect', 'Sonic Mega Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smegacollectplus', 'Sonic Mega Collection Plus');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sgemcollect', 'Sonic Gems Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spccollect', 'Sonic PC Collection');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('sclassiccollect', 'Sonic Classic Collection');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crash1', 'Crash Bandicoot');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashbandicoot1', 'Crash Bandicoot');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crash2', 'Crash Bandicoot 2: Cortex Strikes Back');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashbandicoot2', 'Crash Bandicoot 2: Cortex Strikes Back');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crash3', 'Crash Bandicoot: Warped');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashbandicoot3', 'Crash Bandicoot: Warped');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('ctr', 'Crash Team Racing');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashbash', 'Crash Bash');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashtwoc', 'Crash Bandicoot: The Wrath of Cortex');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('crashbandicoottwoc', 'Crash Bandicoot: The Wrath of Cortex');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spyro1', 'Spyro the Dragon');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spyro2', 'Spyro 2: Ripto''s Rage');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spyro3', 'Spyro: Year of the Dragon');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('spyroetd', 'Spyro: Enter the Dragonfly');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohfm', 'Yu-Gi-Oh! Forbidden Memories');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohdds', 'Yu-Gi-Oh! Dark Duel Stories');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohddm', 'Yu-Gi-Oh! Dungeon Dice Monsters');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohteds', 'Yu-Gi-Oh! The Eternal Duelist Soul');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohdor', 'Yu-Gi-Oh! Duelists of the Roses');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohtsc', 'Yu-Gi-Oh! The Sacred Cards');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohtfk', 'Yu-Gi-Oh!: The Falsebound Kingdom');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohrod', 'Yu-Gi-Oh! Reshef of Destruction');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohsttdd', 'Yu-Gi-Oh! Worldwide Edition: Stairway to the Destined Duel');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohwct2004', 'Yu-Gi-Oh! World Championship Tournament 2004');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2004', 'Yu-Gi-Oh! World Championship Tournament 2004');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohdbt', 'Yu-Gi-Oh! Destiny Board Traveler');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohdod', 'Yu-Gi-Oh! The Dawn of Destiny');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohpockaiba', 'Yu-Gi-Oh! Power of Chaos: Kaiba the Revenge');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohpocjoey', 'Yu-Gi-Oh! Power of Chaos: Joey the Passion');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohcmc', 'Yu-Gi-Oh! Capsule Monster Coliseum');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2005', 'Yu-Gi-Oh! 7 Trials to Glory: World Championship Tournament 2005');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohonline', 'Yu-Gi-Oh! Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioho', 'Yu-Gi-Oh! Online');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohnt', 'Yu-Gi-Oh! Nightmare Troubadour');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxda', 'Yu-Gi-Oh! GX Duel Academy');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2006', 'Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxtf', 'Yu-Gi-Oh! GX Tag Force');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxtf1', 'Yu-Gi-Oh! GX Tag Force');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxsc', 'Yu-Gi-Oh! GX: Spirit Caller');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2007', 'Yu-Gi-Oh! World Championship 2007');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxca', 'Yu-Gi-Oh! GX: Card Almanac');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxtf2', 'Yu-Gi-Oh! GX Tag Force 2');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohwc2008', 'Yu-Gi-Oh! World Championship 2008');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2008', 'Yu-Gi-Oh! World Championship 2008');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxbod', 'Yu-Gi-Oh! GX: The Beginning of Destiny');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohgxtf3', 'Yu-Gi-Oh! GX: Tag Force 3');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2009', 'Yu-Gi-Oh! 5D''s Stardust Accelerator: World Championship 2009');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dswb', 'Yu-Gi-Oh! 5D''s Wheelie Breakers');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dstf4', 'Yu-Gi-Oh! 5D''s Tag Force 4');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2010', 'Yu-Gi-Oh! 5D''s World Championship 2010 Reverse of Arcadia');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dstf5', 'Yu-Gi-Oh! 5D''s Tag Force 5');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dsdd', 'Yu-Gi-Oh! 5D''s Decade Duels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dsdd+', 'Yu-Gi-Oh! 5D''s Decade Duels Plus');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dsmotc', 'Yu-Gi-Oh! 5D''s Duel Transer');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh2011', 'Yu-Gi-Oh! 5D''s World Championship 2011: Over the Nexus');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugioh5dstf6', 'Yu-Gi-Oh! 5D''s Tag Force 6');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohzexal', 'Yu-Gi-Oh! Zexal: Clash! Duel Carnival!');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohmd', 'Yu-Gi-Oh! Millennium Duels');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohdg', 'Yu-Gi-Oh! Duel Generation');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohatfs', 'Yu-Gi-Oh! Arc-V Tag Force Special');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('yugiohlotd', 'Yu-Gi-Oh! Legacy of the Duelist');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('smonk', 'Skullmonkeys');


INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('gdash', 'Geometry Dash');
INSERT OR REPLACE INTO game_abbreviations (abbreviation, twitchGame) VALUES ('geometrydash', 'Geometry Dash');


COMMIT TRANSACTION;