games = {
    'aoe2hd': 'Age of Empires II: HD Edition',
    'pkmnredblue': 'Pokémon Red/Blue',
    'pkmnrb': 'Pokémon Red/Blue',
    'pokemontcg': 'Pokémon Trading Card Game',
    'ppl': 'Pokémon Puzzle League',
    'pkmnyellow': 'Pokémon Yellow: Special Pikachu Edition',
    'pkmny': 'Pokémon Yellow: Special Pikachu Edition',
    'pkmnfrlg': 'Pokémon FireRed/LeafGreen',
    'pmdredblue': 'Pokémon Mystery Dungeon: Blue/Red Rescue Team',
    'pkmnemerald': 'Pokémon Emerald',
    'pkmne': 'Pokémon Emerald',
    'pkmnsnap': 'Pokémon Snap',
    'pkmnstadium': 'Pokémon Stadium',
    'pkmnstadium2': 'Pokémon Stadium 2',
    'pkmnrubysapphire': 'Pokémon Ruby/Sapphire',
    'pkmnrs': 'Pokémon Ruby/Sapphire',
    'pkmncrystal': 'Pokémon Crystal',
    'pkmngoldsilver': 'Pokémon Gold/Silver',
    'pkmngs': 'Pokémon Gold/Silver',
    'pkmndp': 'Pokémon Diamond/Pearl',
    'ppc': 'Pokémon Puzzle Challenge',
    'pkmnpinball': 'Pokémon Pinball',
    'pkmnrumbleblast': 'Pokémon Rumble Blast',
    'pokemonxd': 'Pokémon XD: Gale of Darkness',
    'pkmnredgreen': 'Pokémon RedJP/Green',
    'pkmnxy': 'Pokémon X/Y',
    'pkmnblackwhite': 'Pokémon Black/White',
    'pkmnbw': 'Pokémon Black/White',
    'pkmnoras': 'Pokémon Omega Ruby/Alpha Sapphire',
    'pkmnhgss': 'Pokémon HeartGold/SoulSilver',
    'pkmnblackwhite2': 'Pokémon Black/White Version 2',
    'pkmnb2w2': 'Pokémon Black/White Version 2',
    'pmdeos': 'Pokémon Mystery Dungeon: Explorers of Sky',
    'pkmnrumble': 'Pokémon Rumble',
    'pkmnranger': 'Pokémon Ranger',
    'pkmnplat': 'Pokémon Platinum',
}