games = {
    'aoe2hd': 'Age of Empires II: HD Edition',
    'pkmnredblue': 'Pokémon Red/Blue',
    'pkmnrb': 'Pokémon Red/Blue',
    'pokemontcg': 'Pokémon Trading Card Game',
    'ppl': 'Pokémon Puzzle League',
    'pkmnyellow': 'Pokémon Yellow: Special Pikachu Edition',
    'pkmny': 'Pokémon Yellow: Special Pikachu Edition',
    'pkmnfrlg': 'Pokémon FireRed/LeafGreen',
    'pmdredblue': 'Pokémon Mystery Dungeon: Blue/Red Rescue Team',
    'pkmnemerald': 'Pokémon Emerald',
    'pkmne': 'Pokémon Emerald',
    'pkmnsnap': 'Pokémon Snap',
    'pkmnstadium': 'Pokémon Stadium',
    'pkmnstadium2': 'Pokémon Stadium 2',
    'pkmnrubysapphire': 'Pokémon Ruby/Sapphire',
    'pkmnrs': 'Pokémon Ruby/Sapphire',
    'pkmncrystal': 'Pokémon Crystal',
    'pkmngoldsilver': 'Pokémon Gold/Silver',
    'pkmngs': 'Pokémon Gold/Silver',
    'pkmndp': 'Pokémon Diamond/Pearl',
    'ppc': 'Pokémon Puzzle Challenge',
    'pkmnpinball': 'Pokémon Pinball',
    'pkmnrumbleblast': 'Pokémon Rumble Blast',
    'pokemonxd': 'Pokémon XD: Gale of Darkness',
    'pkmnredgreen': 'Pokémon RedJP/Green',
    'pkmnxy': 'Pokémon X/Y',
    'pkmnblackwhite': 'Pokémon Black/White',
    'pkmnbw': 'Pokémon Black/White',
    'pkmnoras': 'Pokémon Omega Ruby/Alpha Sapphire',
    'pkmnhgss': 'Pokémon HeartGold/SoulSilver',
    'pkmnblackwhite2': 'Pokémon Black/White Version 2',
    'pkmnb2w2': 'Pokémon Black/White Version 2',
    'pmdeos': 'Pokémon Mystery Dungeon: Explorers of Sky',
    'pkmnrumble': 'Pokémon Rumble',
    'pkmnranger': 'Pokémon Ranger',
    'pkmnplat': 'Pokémon Platinum',
    'mm1': 'Mega Man',
    'mm2': 'Mega Man 2',
    'mm3': 'Mega Man 3',
    'mm3rr': 'Mega Man 3: The Robots are Revolting',
    'mm4': 'Mega Man 4',
    'mm5': 'Mega Man 5',
    'mm6': 'Mega Man 6',
    'mm7': 'Mega Man 7',
    'mm8': 'Mega Man 8: Anniversary Edition',
    'mm9': 'Mega Man 9',
    'mm10': 'Mega Man 10',
    'mmww': 'Mega Man: The Wily Wars',
    'mmac': 'Mega Man Anniversary Collection',
    'rmf': 'Mega Man & Bass',
    'mmb': 'Mega Man & Bass',
    'rmfmknc': 'Rockman & Forte: Mirai kara no Chousensha',
    'mm1gb': 'Mega Man: Dr Wily\'s Revenge',
    'mm2gb': 'Mega Man II',
    'mm3gb': 'Mega Man III',
    'mm4gb': 'Mega Man IV',
    'mm5gb': 'Mega Man V',
    'mmx': 'Mega Man X',
    'mmx2': 'Mega Man X2',
    'mmx3': 'Mega Man X3',
    'mmx4': 'Mega Man X4',
    'mmx5': 'Mega Man X5',
    'mmx6': 'Mega Man X6',
    'mmx7': 'Mega Man X7',
    'mmx8': 'Mega Man X8',
    'mmxc': 'Mega Man X Collection',
    'mmxgb': 'Mega Man Xtreme',
    'mmx2gb': 'Mega Man Xtreme 2',
    'mmxcm': 'Mega Man X: Command Mission',
    'mmz': 'Mega Man Zero',
    'mmz2': 'Mega Man Zero 2',
    'mmz3': 'Mega Man Zero 3',
    'mmz4': 'Mega Man Zero 4',
    'mmzc': 'Mega Man Zero Collection',
    'mmzx': 'Mega Man ZX',
    'mmzxa': 'Mega Man ZX Advent',
    'mmbn1': 'Mega Man Battle Network',
    'mmbn2': 'Mega Man Battle Network 2',
    'mmbn3': 'Mega Man Battle Network 3',
    'mmbn4': 'Mega Man Battle Network 4',
    'mmbn4.5': 'Rockman EXE 4.5 Real Operation',
    'mmbn5': 'Mega Man Battle Network 5',
    'mmbn5ds': 'Mega Man Battle Network 5: Double Team DS',
    'mmbn6': 'Mega Man Battle Network 6',
    'mmsf1': 'Mega Man Star Force',
    'mmsf2': 'Mega Man Star Force 2',
    'mmsf3': 'Mega Man Star Force 3',
    'mmbcc': 'Mega Man Battle Chip Challenge',
    'rmeoss': 'Rockman EXE Operate Shooting Star',
    'mmbncx': 'Mega Man Battle Network Chrono X',
    'mmtpb': 'Mega Man: The Power Battle',
    'mm2tbf': 'Mega Man 2: The Power Fighters',
    'rmbf': 'Rockman Battle & Fighters',
    'mm64': 'Mega Man 64',
    'mml': 'Mega Man Legends',
    'mml2': 'Mega Man Legends 2',
    'rmbc': 'Rockman Battle & Chase',
}