disableFilters = True
disableCustomMessage = True

filterMessage = []
commands = {
    '!exit': (None, None),
    '!managebot': (None, None),
    '!reload': (None, None),
    '!reloadcommands': (None, None),
    '!reloadconfig': (None, None),
    '!join': (None, None),
    '!part': (None, None),
    '!emptychat': (None, None),
    '!emptyall': (None, None),
    '!global': (None, None),
    '!say': (None, None),
    '!hello': (None, None),
    '!leave': (None, None),
    '!feature': (None, None),
    '!empty': (None, None),
    '!autorepeat': (None, None),
    '!pyramid': (None, None),
    '!rpyramid': (None, None),
    '!wall': (None, None),
    '!status': (None, None),
    '!title': (None, None),
    '!game': (None, None),
    '!setgame': (None, None),
    '!purge': (None, None),
    '!rekt': (None, None),
    '!command': (None, None),
    '!full': (None, None),
    '!parenthesized': (None, None),
    '!circled': (None, None),
    '!smallcaps': (None, None),
    '!upsidedown': (None, None),
    '!come': (None, None),
    '!autojoin': (None, None),
    '!uptime': (None, None),
    }
commandsStartWith = {
    '!pyramid-': (None, None),
    '!wall-': (None, None),
    '!autorepeat-': (None, None),
    }
noCommandPreCustom = []
noCommandPostCustom = []
